---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQK
  MYSQL_DATABASE: ZW1wbG95ZWVkYgo=
  MYSQL_USER: cm9vdAo=
  MYSQL_PASSWORD: cGFzc3dvcmQK
